export var movies = ["raa", "one", "zero"];
console.log(`Movies are: ${movies}`);
console.log(`Movies are :  ${movies[6]}  `);
console.log(`Movies are :  ${movies[2]}  `);
movies.push("Maharshi");
console.log(`Movies are :  ${movies}  `);
console.log(`Movies are :  ${movies.pop()}  `);
console.log(`Movies are :  ${movies}  `);
movies.unshift("Maharshi");
console.log(`Movies are :  ${movies}  `);
console.log(`Movies are :  ${movies.shift()}  `);
console.log(`Movies are :  ${movies}  `);
